// Code generated by MockGen. DO NOT EDIT.
// Source: dataservice/internal/api/nationalizeapi (interfaces: NationalizeAPI)
//
// Generated by this command:
//
//	mockgen -package nationalizeapi -destination api_mock.go . NationalizeAPI
//

// Package nationalizeapi is a generated GoMock package.
package nationalizeapi

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNationalizeAPI is a mock of NationalizeAPI interface.
type MockNationalizeAPI struct {
	ctrl     *gomock.Controller
	recorder *MockNationalizeAPIMockRecorder
}

// MockNationalizeAPIMockRecorder is the mock recorder for MockNationalizeAPI.
type MockNationalizeAPIMockRecorder struct {
	mock *MockNationalizeAPI
}

// NewMockNationalizeAPI creates a new mock instance.
func NewMockNationalizeAPI(ctrl *gomock.Controller) *MockNationalizeAPI {
	mock := &MockNationalizeAPI{ctrl: ctrl}
	mock.recorder = &MockNationalizeAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNationalizeAPI) EXPECT() *MockNationalizeAPIMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockNationalizeAPI) Get(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNationalizeAPIMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNationalizeAPI)(nil).Get), arg0, arg1)
}
